name: Propose Build
description: Submit your own build to the project.
title: "Build: New"
labels:
  - build

body:
  - type: input
    id: build_name
    attributes:
      label: Build Name
      placeholder: Anti-Slug Build
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Build Type
      options:
        - Survivor
        - Killer
    validations:
      required: true

  - type: input
    id: perk1
    attributes:
      label: Perk 1
      placeholder: First perk
    validations:
      required: true

  - type: input
    id: perk2
    attributes:
      label: Perk 2
      placeholder: Second perk
    validations:
      required: true

  - type: input
    id: perk3
    attributes:
      label: Perk 3
      placeholder: Third perk
    validations:
      required: true

  - type: input
    id: perk4
    attributes:
      label: Perk 4
      placeholder: Fourth perk
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      placeholder: Your name
    validations:
      required: true
